name: Android CI

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
        
    - name: Find exact compilation errors
      run: |
        echo "=== COMPILING KOTLIN TO SEE EXACT ERRORS ==="
        ./gradlew :app:compileClientDebugKotlin --stacktrace --info 2>&1 | grep -A 10 -B 5 "error:\|PRDownloader\|WheelPicker\|Unresolved reference" || echo "No specific errors found in grep"
        
        echo "=== FULL BUILD ATTEMPT ==="
        ./gradlew :app:assembleClientDebug --continue --stacktrace
        
    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          app/build/reports/
          build/reports/
        retention-days: 30
        
    - name: Upload APK if exists
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: app-client-debug
        path: app/build/outputs/apk/client/debug/app-client-debug.apk
        retention-days: 30
        
    - name: Show result
      if: always()
      run: |
        echo "=== BUILD COMPLETED ==="
        if [ -f "app/build/outputs/apk/client/debug/app-client-debug.apk" ]; then
          echo "✅ SUCCESS: APK built!"
          ls -la app/build/outputs/apk/client/debug/
        else
          echo "❌ Build failed - checking for logs..."
          find . -name "*.log" -exec echo "=== LOG FILE: {} ===" \; -exec tail -20 {} \; 2>/dev/null | head -100 || echo "No log files found"
        fi
