name: Android CI

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Get exact Kotlin errors
      run: |
        echo "=== COMPILING TO SEE EXACT ERRORS ==="
        ./gradlew :app:compileClientDebugKotlin --stacktrace 2>&1 | grep -A 10 -B 5 "error:" | head -50 || echo "No specific errors found"
        
        echo "=== SEARCHING FOR COMMON ISSUES ==="
        ./gradlew :app:compileClientDebugKotlin 2>&1 | grep -A 5 -B 5 "PRDownloader\|WheelPicker\|Unresolved\|error:" | head -30 || echo "No pattern matches found"
        
    - name: Try build with continue
      run: ./gradlew :app:assembleClientDebug --continue --stacktrace
