name: Debug Build

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  debug-build:
    name: Debug Dependencies and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Gradle version info
      run: ./gradlew --version
      
    - name: Check Android dependencies
      run: ./gradlew :app:dependencies --configuration implementation
      
    - name: Check all configurations
      run: |
        ./gradlew :app:dependencies --configuration compileClasspath
        ./gradlew :app:dependencies --configuration runtimeClasspath
        
    - name: Clean project
      run: ./gradlew clean
      
    - name: Try build with stacktrace
      run: ./gradlew :app:assembleClientDebug --stacktrace --continue
      
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: |
          **/build/reports/
          **/build/outputs/
